// Generated by CoffeeScript 1.4.0

describe("node-cache", function() {
  it("is healthy", function() {
    return expect(Cache).toBeTruthy();
  });
  it("save and get element", function() {
    Cache.set(1, "FOO", 100);
    return expect(Cache.get(1)).toEqual("FOO");
  });
  it("save and remove element", function() {
    Cache.set(1, "FOO", 100);
    expect(Cache.get(1)).toEqual("FOO");
    expect(Cache.remove(1)).toBe(true);
    expect(Cache.remove(1)).toBe(false);
    return expect(Cache.get(1)).toEqual(null);
  });
  return it("element expires", function() {
    var getter;
    Cache.set(5, "FOO5", 2);
    expect(Cache.get(5)).toEqual("FOO5");
    getter = function() {
      return expect(Cache.get(5)).toEqual(null);
    };
    return setTimeout(getter, 25000);
  });
});
